name: infra.system_actions
version: 0.2.0
compatible_core_versions: ">=0.4.2"
description: "系统操作模块：提供一些系统级别操作的API的模块。例如 pipeline 租约、复制文件模版等等。"
dependencies:
  - infra.project_context
  - modules.strategy
  - modules.tag
changelog:
  - version: "0.2.0"
    changes:
      - 标准化模块，标准化文档以及对外API
      - 修改了暴露的API参数，函数，防止外部模块直接调用包内非公开接口
      - 正式版本之前所有API标注beta状态
  - version: "0.1.0"
    changes:
      - 初始化模块，完成基础功能
      - 提供缓存清理，pipeline 租约，脚手架创建等系统级别操作的API，方便其他模块使用
