# 模块元数据
name: infra.discovery
version: "0.2.1"
compatible_core_versions: ">=0.4.0"
description: "发现模块：自动发现一些带有特征的文件/类/文件夹的模块，用来服务于用户自定义的功能文件和类。"
dependencies: []
changelog:
  - version: "0.2.1"
    changes:
      - 标准化模块，标准化文档以及对外API
      - 修改了暴露的API参数，函数，防止外部模块直接调用包内非公开接口
      - 正式版本之前所有API标注beta状态
  - version: "0.1.1"
    changes:
      - 新增 FileUtils（单个文件操作）
      - 新增 FileDiscovery（批量文件发现）
  - version: "0.1.0"
    changes:
      - 初始化模块，完成基础功能
      - 快捷发现文件/类/文件夹等，方便外部调用
