name: infra.export_import
version: 0.2.0
compatible_core_versions: ">=0.4.0"
description: "导入导出模块：打包，压缩等等对批量或者单个文件的操作模块，主要服务于文件导入导出功能。"
dependencies: []
changelog:
  - version: "0.2.0"
    changes:
      - 标准化模块，标准化文档以及对外API
      - 修改了暴露的API参数，函数，防止外部模块直接调用包内非公开接口
      - 正式版本之前所有API标注beta状态
  - version: "0.1.0"
    changes:
      - 初始化模块，完成基础功能
      - 支持目录收集（运行时目录排除）
      - 支持zip打包和解压
      - 支持安装前冲突预检，支持 拒绝/跳过/复写 行为
