"""V2-09：将快照 ``settings_snapshot`` 写入 userspace ``settings.py``。"""

from __future__ import annotations

import logging
import os
import pprint
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any, Dict, Optional, Tuple

from core.infra.project_context.path_manager import PathManager
from core.modules.data_manager import DataManager
from core.modules.strategy.services.launcher.strategy_settings_service import StrategySettingsService
from core.modules.strategy.services.launcher.workbench import fetch_workbench_snapshot_by_snapshot_id

logger = logging.getLogger(__name__)


def _atomic_write_text(target_path: Path, content: str, encoding: str = "utf-8") -> None:
    """与 ``core.ui.bff.shared.file_ops.atomic_write_text`` 同语义，避免 launcher 依赖 BFF 包初始化链。"""
    target_path.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile("w", encoding=encoding, dir=target_path.parent, delete=False) as tmp:
        tmp.write(content)
        temp_path = Path(tmp.name)
    os.replace(str(temp_path), str(target_path))


def _backup_settings_file(strategy_name: str) -> None:
    settings_file = PathManager.strategy_settings(strategy_name)
    if settings_file.is_file():
        backup_path = settings_file.with_suffix(settings_file.suffix + ".bak")
        backup_path.write_text(settings_file.read_text(encoding="utf-8"), encoding="utf-8")


def _write_settings_py(strategy_name: str, settings: Dict[str, Any], pretty: bool) -> None:
    settings_file = PathManager.strategy_settings(strategy_name)
    if pretty:
        literal = pprint.pformat(dict(settings or {}), width=100, sort_dicts=True)
    else:
        literal = repr(dict(settings or {}))
    content = (
        "# Auto-generated by Strategy Workbench (apply snapshot version to userspace).\n"
        "# Manual edits are allowed; next save from Workbench may reformat this file.\n\n"
        f"settings = {literal}\n"
    )
    _atomic_write_text(settings_file, content)


def apply_workbench_snapshot_settings_to_userspace(
    *,
    strategy_name: str,
    snapshot_id: int,
    pretty: bool = False,
) -> Tuple[Optional[Dict[str, Any]], Optional[str]]:
    """
    读取一行快照 → 规范化 settings → 备份并原子写入 ``settings.py`` → 刷新该行 ``updated_at``。

    成功返回 ``({"applied": True, "strategy_name", "version_id"}, None)``。
    """
    name = str(strategy_name or "").strip()
    sid = int(snapshot_id)
    if not name or sid <= 0:
        return None, "参数无效"

    row = fetch_workbench_snapshot_by_snapshot_id(name, sid)
    if not row:
        return None, "快照不存在"

    settings_snapshot = row.get("settings_snapshot") or {}
    normalized, err = StrategySettingsService.normalize_runtime_settings(
        strategy_name=name,
        api_settings=settings_snapshot,
    )
    if err or not normalized:
        return None, err or "settings 校验失败"

    try:
        _backup_settings_file(name)
        _write_settings_py(name, normalized, pretty)
    except Exception as e:
        logger.exception("apply-settings 写盘失败 strategy=%s snapshot_id=%s", name, sid)
        return None, f"写盘失败: {e}"

    model = DataManager().get_table("sys_strategy_workbench_snapshot")
    if model is None:
        logger.error("sys_strategy_workbench_snapshot 未注册，写盘已成功")
        return None, "存储不可用"

    try:
        n = int(model.touch_snapshot_updated_at(name, sid) or 0)
        if n <= 0:
            return None, "更新快照时间失败: 行不存在或无法更新"
    except Exception as e:
        logger.exception("touch_snapshot_updated_at failed")
        return None, f"更新快照时间失败: {e}"

    return (
        {
            "applied": True,
            "strategy_name": name,
            "version_id": f"v{sid}",
        },
        None,
    )
