"""worker.json profile：并行度探针、默认值、配置解析。"""
from core.infra.job_pipeline.profile.constants import (
    CALENDAR_SLICE_RUNTIME_DEFAULTS,
    DEFAULT_PRICE_ENTITIES_PER_JOB,
    DISPATCH_DEFAULTS_BY_PROFILE,
    ENUMERATOR_DISPATCH_DEFAULTS,
    ENUMERATOR_STRATEGY_CALENDAR_SLICE_KEYS,
    ENUMERATOR_STRATEGY_DISPATCH_KEYS,
    JOB_PIPELINE_PROFILE_NAMES,
    PRICE_FACTOR_DISPATCH_DEFAULTS,
    PRICE_STRATEGY_DISPATCH_KEYS,
    USER_PIPELINE_POOL_KEYS,
    WorkerProfiles,
)
from core.infra.job_pipeline.profile.probe import WorkerProbe
from core.infra.job_pipeline.profile.resolver import (
    job_pipeline_profile,
    pipeline_max_parallel_jobs_cap,
    pipeline_reserve_cores,
    profile_dispatch_config,
    profile_entity_based_performance,
    profile_calendar_slice_config,
    profile_max_parallel_jobs_cap,
    profile_reserve_cores,
    resolve_entity_based_performance_for_profile,
    resolve_pipeline_workers,
    resolve_worker_profile,
)

__all__ = [
    "CALENDAR_SLICE_RUNTIME_DEFAULTS",
    "DEFAULT_PRICE_ENTITIES_PER_JOB",
    "DISPATCH_DEFAULTS_BY_PROFILE",
    "ENUMERATOR_DISPATCH_DEFAULTS",
    "ENUMERATOR_STRATEGY_CALENDAR_SLICE_KEYS",
    "ENUMERATOR_STRATEGY_DISPATCH_KEYS",
    "JOB_PIPELINE_PROFILE_NAMES",
    "PRICE_FACTOR_DISPATCH_DEFAULTS",
    "PRICE_STRATEGY_DISPATCH_KEYS",
    "USER_PIPELINE_POOL_KEYS",
    "WorkerProfiles",
    "WorkerProbe",
    "job_pipeline_profile",
    "pipeline_max_parallel_jobs_cap",
    "pipeline_reserve_cores",
    "profile_calendar_slice_config",
    "profile_dispatch_config",
    "profile_entity_based_performance",
    "profile_max_parallel_jobs_cap",
    "profile_reserve_cores",
    "resolve_entity_based_performance_for_profile",
    "resolve_pipeline_workers",
    "resolve_worker_profile",
]
