name: infra.update
version: 0.1.0
compatible_core_versions: ">=0.4.1"
description: "升级模块：提供一些app升级相关的操作的模块。例如数据迁移脚本注册表，自动化安装内核等等。"
dependencies: []
changelog:
  - version: "0.1.0"
    changes:
      - 初始化模块，完成基础功能
      - 标准化模块，标准化文档以及对外API
      - 修改了暴露的API参数，函数，防止外部模块直接调用包内非公开接口
      - 正式版本之前所有API标注beta状态
      - updater 基础能力（CLI / 后续 UI 一键升级预留）

