"""仿真 version 目录文件名常量。"""

RUNTIME_ENV_FILE = "runtime_env.json"
ENTITY_IDS_FILE = "entity_ids.txt"
PERFORMANCE_FILE = "performance.json"
OVERALL_REPORT_FILE = "overall_report.json"
ENTITY_LIST_FILE = "entity_list.json"
TRADES_FILE = "trades.json"
EQUITY_CURVE_FILE = "equity_curve.json"

ENTITIES_SUBDIR = "entities"

STOCK_INVESTMENTS_SUFFIX = "_stock_investments.csv"
GOAL_ACHIEVEMENTS_SUFFIX = "_goal_achievements.csv"
SIGNAL_SNAPSHOTS_SUFFIX = "_signal_snapshots.csv"
PRICE_INVESTMENTS_SUFFIX = "_investments.csv"

ENUM_REPORT_FILES = (
    OVERALL_REPORT_FILE,
    ENTITY_LIST_FILE,
    PERFORMANCE_FILE,
)
PRICE_REPORT_FILES = ENUM_REPORT_FILES
PORTFOLIO_REPORT_FILES = ENUM_REPORT_FILES

ENUM_VERSION_REQUIRED_FILES = (
    RUNTIME_ENV_FILE,
    ENTITY_IDS_FILE,
    *ENUM_REPORT_FILES,
)
PRICE_VERSION_REQUIRED_FILES = (
    RUNTIME_ENV_FILE,
    ENTITY_IDS_FILE,
    *PRICE_REPORT_FILES,
)
PORTFOLIO_VERSION_REQUIRED_FILES = (
    RUNTIME_ENV_FILE,
    *PORTFOLIO_REPORT_FILES,
)

__all__ = [
    "ENTITIES_SUBDIR",
    "ENTITY_IDS_FILE",
    "ENTITY_LIST_FILE",
    "ENUM_REPORT_FILES",
    "ENUM_VERSION_REQUIRED_FILES",
    "EQUITY_CURVE_FILE",
    "GOAL_ACHIEVEMENTS_SUFFIX",
    "OVERALL_REPORT_FILE",
    "PERFORMANCE_FILE",
    "PRICE_INVESTMENTS_SUFFIX",
    "PRICE_REPORT_FILES",
    "PRICE_VERSION_REQUIRED_FILES",
    "PORTFOLIO_REPORT_FILES",
    "PORTFOLIO_VERSION_REQUIRED_FILES",
    "RUNTIME_ENV_FILE",
    "SIGNAL_SNAPSHOTS_SUFFIX",
    "STOCK_INVESTMENTS_SUFFIX",
    "TRADES_FILE",
]
