"""仿真 version 目录与扫描日期目录文件名常量。"""

RUNTIME_ENV_FILE = "runtime_env.json"
EFFECTIVE_SETTINGS_FILE = "effective_settings.json"
SETTINGS_FILE = "settings.json"
SCOPE_FILE = "scope.json"
ENTITY_IDS_FILE = "entity_ids.txt"
PERFORMANCE_FILE = "performance.json"
OVERALL_REPORT_FILE = "overall_report.json"
ENTITY_LIST_FILE = "entity_list.json"
TRADES_FILE = "trades.json"
EQUITY_CURVE_FILE = "equity_curve.json"

ANALYSIS_SUBDIR = "analysis"
ANALYSIS_SOURCE_JSON = "source.json"
ANALYSIS_REPORT_JSON = "report.json"
ANALYSIS_SOURCE_FILE = f"{ANALYSIS_SUBDIR}/{ANALYSIS_SOURCE_JSON}"
ANALYSIS_REPORT_FILE = f"{ANALYSIS_SUBDIR}/{ANALYSIS_REPORT_JSON}"

ENTITIES_SUBDIR = "entities"

STOCK_INVESTMENTS_SUFFIX = "_stock_investments.csv"
GOAL_ACHIEVEMENTS_SUFFIX = "_goal_achievements.csv"
SIGNAL_SNAPSHOTS_SUFFIX = "_signal_snapshots.csv"
PRICE_INVESTMENTS_SUFFIX = "_investments.csv"

ENUM_REPORT_FILES = (
    OVERALL_REPORT_FILE,
    ENTITY_LIST_FILE,
    PERFORMANCE_FILE,
)
PRICE_REPORT_FILES = ENUM_REPORT_FILES
PORTFOLIO_REPORT_FILES = ENUM_REPORT_FILES

ENUM_VERSION_REQUIRED_FILES = (
    RUNTIME_ENV_FILE,
    ENTITY_IDS_FILE,
    *ENUM_REPORT_FILES,
)
PRICE_VERSION_REQUIRED_FILES = (
    RUNTIME_ENV_FILE,
    ENTITY_IDS_FILE,
    *PRICE_REPORT_FILES,
)
PORTFOLIO_VERSION_REQUIRED_FILES = (
    RUNTIME_ENV_FILE,
    *PORTFOLIO_REPORT_FILES,
)

SCAN_SUMMARY_FILE = "scan_summary.json"
SCAN_OPPORTUNITIES_FILE = "opportunities.csv"

__all__ = [
    "ANALYSIS_REPORT_FILE",
    "ANALYSIS_REPORT_JSON",
    "ANALYSIS_SOURCE_FILE",
    "ANALYSIS_SOURCE_JSON",
    "ANALYSIS_SUBDIR",
    "ENTITIES_SUBDIR",
    "ENTITY_IDS_FILE",
    "ENTITY_LIST_FILE",
    "ENUM_REPORT_FILES",
    "ENUM_VERSION_REQUIRED_FILES",
    "EQUITY_CURVE_FILE",
    "GOAL_ACHIEVEMENTS_SUFFIX",
    "OVERALL_REPORT_FILE",
    "PERFORMANCE_FILE",
    "PRICE_INVESTMENTS_SUFFIX",
    "PRICE_REPORT_FILES",
    "PRICE_VERSION_REQUIRED_FILES",
    "PORTFOLIO_REPORT_FILES",
    "PORTFOLIO_VERSION_REQUIRED_FILES",
    "RUNTIME_ENV_FILE",
    "SCAN_OPPORTUNITIES_FILE",
    "SCAN_SUMMARY_FILE",
    "SCOPE_FILE",
    "SETTINGS_FILE",
    "EFFECTIVE_SETTINGS_FILE",
    "SIGNAL_SNAPSHOTS_SUFFIX",
    "STOCK_INVESTMENTS_SUFFIX",
    "TRADES_FILE",
]
