# Auto-migrated simulation block to execution/assumption/risk_control.
settings = {'is_enabled': True,
 'meta': {'key': 'stock_based_rsi',
          'display_name': 'RSI超跌反弹 + 财报正常',
          'description': '演示策略：RSI(14) '
                         '超卖触发买入，并要求最新已披露季度净利润同比不低于阈值。演示意义：技术信号负责「何时看」，基本面负责「能不能买」——避免在盈利恶化的下跌里接飞刀。',
          'keywords': ['性能测试'],
          'details': {'entry': ['RSI(14) 低于超卖阈值（见 core.rsi_oversold_threshold，默认 20）',
                                '最新已披露季度 netprofit_yoy ≥ core.min_netprofit_yoy（默认 0，即不同比下滑）',
                                '财报 PIT 由 stock.finance.quarterly 的 ann_date 时间轴 + '
                                'contract.until 切片保证']}},
 'market_profile': 'china_a_stock',
 'core': {'rsi_oversold_threshold': 20, 'min_netprofit_yoy': 0.0},
 'data': {'base': {'data_key': 'stock.kline.daily',
                   'params': {'adjust': 'qfq'},
                   'indicators': {'rsi': [{'length': 14}]}},
          'required': [{'data_key': 'stock.finance.quarterly', 'params': {}}],
          'min_required_records': 30},
 'simulation': {'retention': {'max_output_versions': 5},
                'execution': {'start_date': '20240101',
                              'end_date': '20241231',
                              'mode': 'entity_based',
                              'steps': ['check_settlement',
                                        'check_stop_loss',
                                        'check_take_profit',
                                        'check_expiration']},
                'assumption': {'template': 'custom',
                               'tradability': {'monitor_price': 'close',
                                               'enter_price': 'next_open',
                                               'exit_price': 'close',
                                               'slippage': {'enter_bps': 5.0, 'exit_bps': 5.0},
                                               'edges': {'no_next_tick': 'skip_trade',
                                                         'allow_enter_at_limit_up': False,
                                                         'allow_exit_at_limit_down': False},
                                               'liquidity': {'max_participation_rate': 0.1,
                                                             'participation_on_exceed': 'clip'},
                                               'delisted_exit_price': 'last_tradable_close'}},
                'risk_control': {'skip_enter_when': [], 'force_exit_when': []}},
 'goal': {'expiration': {'fixed_window_in_days': 30, 'mode': 'open_day'},
          'stop_loss': {'stages': [{'name': 'loss20%', 'ratio': -0.2, 'close_invest': True}]},
          'take_profit': {'stages': [{'name': 'win20%', 'ratio': 0.2, 'close_invest': True}]}},
 'sampling': {'use_sampling': True,
              'strategy': 'pool',
              'sampling_amount': 500,
              'pool': {'stock_ids': ['600000.SH']}},
 'enumerator': {'is_verbose': False},
 'fees': {'commission_rate': 0.00025,
          'min_commission': 5.0,
          'stamp_duty_rate': 0.001,
          'transfer_fee_rate': 0.0},
 'portfolio': {'base_version': 'latest',
               'initial_capital': 100000,
               'allocation': {'mode': 'equal_capital',
                              'max_portfolio_size': 10,
                              'max_weight_per_stock': 0.3,
                              'lots_per_trade': 1,
                              'kelly_fraction': 0.5,
                              'skip_trade_when_insufficient': True},
               'output': {'save_trades': True, 'save_equity_curve': True}},
 'scanner': {'adapters': ['console'],
             'use_strict_previous_trading_day': False,
             'max_cache_days': 10,
             'watch_list': ''}}
