# 模块元数据
name: infra.db
version: "0.3.1"
compatible_core_versions: ">=0.4.0"
description: "数据库模块：解析用户数据表声明，提供数据库操作接口，对多数据库进行统一管理。"
dependencies:
  - infra.project_context
changelog:
  - version: "0.3.1"
    changes:
      - 标准化模块，标准化文档以及对外API
      - 修改了暴露的API参数，函数，防止外部模块直接调用包内非公开接口
      - 正式版本之前所有API标注beta状态
  - version: "0.3.0"
    changes:
      - 引擎引入duckdb以及一系列解析器
      - 对duckdb做默认checkpoint的操作
      - 对建表进行更安全的判断，确保不会覆盖存在的表
  - version: "0.2.0"
    changes:
      - 增加入方言解析器，支持mysql和pgsql
      - 重新定义模块配置声明，引入用户空间的common.json来配置所使用的数据库
  - version: "0.1.0"
    changes:
      - 初始化模块，完成基础功能
      - 单例模式
      - 支持pgsql
      - 支持schema声明式建表
